version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: simrs-app
    networks:
      - default
      - dokploy-network
    environment:
      - DB_HOST=db
      - DB_NAME=simrs
      - DB_USER=root
      - DB_PASSWORD=secret
      - YII_ENV=prod
      - YII_DEBUG=false
    depends_on:
      - db
    volumes:
      - assets_data:/var/www/html/web/assets
    command: sh -c "chown -R www-data:www-data /var/www/html/web/assets && php-fpm"

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: simrs-web
    restart: always
    networks:
      - default
      - dokploy-network
    depends_on:
      - app
    volumes:
      - assets_data:/var/www/html/web/assets

  db:
    image: mysql:5.7
    networks:
      - default
      - dokploy-network
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=simrs
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

networks:
  dokploy-network:
    external: true

volumes:
  assets_data:
  db_data:

